### ISSUE TITLE
Considering all fields as mandatory

### ISSUE THREAD

**Issue by rameshputta79** [marianfoo/ui5-cc-excelUpload#202]
Hi,
I have a Odata V4 application which I developed using restful abap.
Using the following guide , I was able to add the 'excel Upload' button on my list report to mass upload data from excel file.

https://marianfoo.github.io/ui5-cc-excelUpload/pages/GettingStarted/

But, it considering all the fields as mandatory while uploading. Is there anyway we could skip this and only make few fields as mandatory?
And also is it possible to add validation to the data thats being uploaded?

**Comment by marianfoo** [comment]
Hi Ramesh
Thank you for using my control.
Please check the following:
- update the version (currently 0.16.4, i fixed a bugs concering validation of mandatory fields)
- only use the template you can download in the dialog
Please also post a screenshot with the errors and the excel template.

Your questions:
### Mandatory fields
The control is using metadata to check mandatory fields. If you defined fields mandatory, they are checked by the control.
You can check **additional** fields by defining the parameter `mandatoryFields`. See the documentation:
https://marianfoo.github.io/ui5-cc-excelUpload/pages/Configuration/#mandatoryfields

### Custom Checks
You can check the fields when uploading the excel to the app (not to the backend) with event `checkBeforeRead`.  
I´m using this in my example apps. See here:
https://github.com/marianfoo/ui5-cc-excelUpload/blob/ba4a4f275211af7754d8b11069c26aa666d5fc75/examples/packages/ordersv4fe/webapp/ext/ObjectPageExtController.js#L24-L43

**Comment by rameshputta79** [comment]
Hi Marian,
Thanks for the tool and your support.
None of my fields are mandatory (except the key fields). It gives me the following error while trying to upload. But there is an option to 'Continue anyway' :).

![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/45cb3122-ec1e-4195-b4b3-3dd7d0f078f4)

Also, I noticed following:
1. After uploading, the records are being stored as a draft. Can we save them directly into the database ? Because, customer may not want to go into each record and save them individually.
2. If I try to upload the same excel file again with no change in data, it just keep processing forever.

thanks.

**Comment by marianfoo** [comment]
No worries :)

The button "Continue anyway" is activated by default because of maybe wrong errors.
It seems i read the metadata wrong. Can you post the metadata.xml here?

You can set the option `activateDraft` to true:
https://marianfoo.github.io/ui5-cc-excelUpload/pages/Configuration/#activatedraft

When it's processing forever, there is probably an error.
Can you do that same thing again and post a screenshot of your console.
Thanks!

**Comment by rameshputta79** [comment]
Hi Marian,

where exactly I should set the activateDraft to 'True' ?
Sorry, I am more of a backend developer and new to UI5.

And i do not see any termination happening in the backend when its processing forever.

**Comment by marianfoo** [comment]
Hi Ramesh,

the many error messages are due to the fact that I consider all fields with "Nullable="false"" as mandatory and must be filled.
I think I will add an option to turn this off or on.
Can you explain to me why all these fields have "Nullable="false""?

**Comment by rameshputta79** [comment]
Not sure. By default it took "Nullable = false" for all fields. 
If I change all fields to "Nullable = True" , would that get rid of these errors ?

**Comment by rameshputta79** [comment]
Ok, thank you ! Let me try that and let you know.

**Comment by marianfoo** [comment]
I just pushed version `0.17.0`.
In this the error is fixed that `SAP__Messages` is defined as mandatory field.
Can you please check if this field is still in the error message?

**Comment by rameshputta79** [comment]
Marian, I Updated nullable = True but still see the same messages
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/50b3963c-8835-447a-862c-5f4477e95ebd)
and also SAP__Message is still there.
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/10a3646f-276f-402d-88ff-335cdb8596e8)

**Comment by marianfoo** [comment]
Hi Ramesh,
two fixes with version ["0.17.1"](https://www.npmjs.com/package/ui5-cc-excelupload/v/0.17.1):
- i handled "SAP__Messages" for V4 wrong, this should be now fixed
- Boolean was parsed wrong, this should be fixed

When your metadata show "Nullable=true", is should definitly not be seen as mandatory anymore. Please check your cache or anything else. I could not reproduce this error.
I set `Deliverynum` to `Nullable="true"` and the error was not there anymore.
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/13335743/911d5eec-ab2c-48b7-970e-541ab5e38f86)
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/13335743/87264f1f-ff27-4b79-a88f-4c967ca5a150)

Please update the version and confirm these errors are fixed for you

**Comment by marianfoo** [comment]
I´ve added a new option to skip all those mandatory checks, even though i think this is not your best solution here.  
As you mentioned earlier you want to activate the drafts.
Please use for the options version [`0.17.2`](https://www.npmjs.com/package/ui5-cc-excelupload/v/0.17.2)
So your code would need to look like:
```js
this.excelUpload = await this._controller.getAppComponent().createComponent({
	usage: "excelUpload",
	async: true,
	componentData: {
		context: this,
		activateDraft: true,
                skipMandatoryFieldCheck: true
	}
});
```

**Comment by rameshputta79** [comment]
Thanks Marian,
- activateDraft: true  works now, its not saving it as a draft anymore but directly into the database.
- skipMandatoryFieldCheck: true is basically skipping all the fields ( Even its skipping the keys fields too which I do not want to ).
- Can we do something about this message? I get this when I leave this field as blank.
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/60b2e2a5-ae6e-47f8-a61d-95ec0e5e08d1)

**Comment by marianfoo** [comment]
The error with the boolean should be fixed by the newest version. Did you update?

You can still check for fields with the option `mandatoryFields`:
```js
mandatoryFields: ["Deliverynum","StatusDesc"]
```
https://marianfoo.github.io/ui5-cc-excelUpload/pages/Configuration/#mandatoryfields

**Comment by rameshputta79** [comment]
- Yes, I have the latest version (v0_17_3) but I still get the following error for the Boolean column.
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/0678eaee-13b6-4752-8230-2aa10432d406)

- Now I could choose the fields which supposed to be mandatory using mandatoryFields . Thank you , but is there any way we can hide 'Continue anyway' button when the mandatory fields are not filled?
![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/400a2220-2658-4cf6-8487-bd8b94c8cbc5)

**Comment by rameshputta79** [comment]
- Somehow, I do not see the message for the Boolean value anymore.  - which is good. 
- And using strict: 'True' got rid of the 'Continue Anyway'  button - thank you!

One last thing ( I promise :)) . I think I mentioned this before as well. 
- when I try to upload the duplicate record,  the screen processing forever. I do not see its erroring out anywhere in the backend code. Is there anyway  we could handle this error right on the screen ?

![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/40f78d13-ebea-4e62-9277-fdfd553f77f6)

![image](https://github.com/marianfoo/ui5-cc-excelUpload/assets/121116258/63bc3de6-3c86-4ab2-ae64-c307671c3272)

**Comment by rameshputta79** [comment]
Marian, 
Thank you so much for your help.  Really appreciate you taking time and helping others. 
I am going to implement this in my V2 application soon and touch base with you again if needed.

thank you again.

**Comment by rameshputta79** [comment]
Hi Marian,
I am re-opening this thread as I am having an issue.
The excel upload works fine when I do the 'Application preview' from BAS. But when I deploy my application to the cloud foundry, the excel upload button does not work. When I click on it, it spins forever without any backend error.
